site_name: AGG Strategic Partnership
site_url: https://agg.plantinformatics.io/strategic-partnership
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - toc.integrate
    - toc.follow