# When ever any commit is pushed to the main branch, this action will auto trigger and update 
# https://agg.plantinformatics.io/strategic-partnership/
# NOTE: A hard refresh might be needed to see the changes (ctrl + R)

name: prod__auto-deploy

on:
  push:
    branches:
      - main  # Trigger on pushes to master branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Pull latest changes
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh $USER@$HOST <<EOF
          cd documentation/strategic-partnership-website
          git fetch origin  
          git reset --hard origin/main
        EOF
